language: ruby
os:
  - linux
  - osx
install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update >/dev/null
    sudo apt-get install -y zsh
    sudo apt-get install shellcheck
  else
    brew update >/dev/null
    brew install zsh
    brew install shellcheck
  fi
script: make ci
notifications:
  email: false
