#!/bin/zsh
set -e

# link to ~ and cd to it
cd ..
cp -rf dotfiles ~/.dotfiles
cd ~/.dotfiles

# setup git credentials
echo "setup git fake user/email"
git config --global user.name "nguyentodo"
git config --global user.email "hi@nguyentodo.dev"

# bootstrap the mighty
echo "boostraping..."
./script/bootstrap

# load zshrc and check if antibody is working
echo "sourcing ~/.zshrc"
# shellcheck disable=SC1090
source ~/.zshrc || true

test "$(antibody list | wc -l)" -gt 5 || {
	echo "expecting 5+ bundles loaded" >&2
	exit 1
}
